# Generated by Django 4.1.7 on 2023-02-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dis', models.TextField()),
                ('minPrice', models.IntegerField()),
                ('maxPrice', models.IntegerField()),
            ],
        ),
    ]
